### ISSUE TITLE
Have you been able to publish the package to meteor?

### ISSUE THREAD

**Issue by sherryxiao1988** [qge/nova-i18n-zh-cn#1]
I've been having issues when running meteor publish --create. Also tried to install your package through meteor add qge:nova-i18n-zh-cn, but it says this package doesn't exist.

**Comment by qge** [comment]
Run: meteor add qge:i18n-zh-ch to add the pacakge.
https://atmospherejs.com/qge/i18n-zh-ch

You have to put your package inside your Telescope app, go to Telescope/packages/your-package, and then run meteor publish --create.

**Comment by sherryxiao1988** [comment]
Thanks! Solved my problem :)
